name: blood_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5+1


  # Firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
